---
apiVersion: v1
kind: Service
metadata:
  name: simple-server
  labels:
      app: simple-server-app
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: simple-server-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
  labels:
    app: simple-server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-server-app
  template:
    metadata:
      labels:
        app: simple-server-app
    spec:
      containers:
      - name: app
        image: ezbin/simple-server:latest
        imagePullPolicy: Always
        ports:
        - name: www
          protocol: TCP
          containerPort: 80
